# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'balance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for balance

  target 'balanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'balanceUITests' do
    # Pods for testing
  end

  pod 'SQLite.swift', '~> 0.12.0'
  pod 'WWCalendarTimeSelector', :git => 'https://github.com/wvabrinskas/WWCalendarTimeSelector', :branch => 'swift5'
  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift', '~> 5.0.1'

end
